#cloud-config

# users:
# - name: cloudservice
#   uid: 2000

write_files:
- path: /etc/systemd/system/securely.service
  permissions: 0644
  owner: root
  content: |
    [Unit]
    Description=Securely stack using docker compose

    [Service]
    ExecStart=/usr/bin/docker run --name securely -v /root/.docker:/root/.docker -v /var/run/docker.sock:/var/run/docker.sock -v "/etc/securely-app:/etc/securely-app" -w="/etc/securely-app" docker/compose:1.24.0 up elasticsearch logstash kibana watchtower proxy
    ExecStop=/usr/bin/docker stop securely && docker rm $_

- path: /tmp/docker-compose.diff
  permissions: 0644
  owner: root
  content: |
    diff --git a/docker-compose.yml b/docker-compose.yml
    index 1c7b6ce..50d0784 100644
    --- a/docker-compose.yml
    +++ b/docker-compose.yml
    @@ -107,6 +107,11 @@ networks:

     volumes:
       esdata:
    +    driver: local
    +    driver_opts:
    +      o: bind
    +      type: none
    +      device: /mnt/disks/nvme/elasticsearch
       logstash-backup:

     # NOTE

runcmd:
- mkdir /mnt/stateful_partition/root
- mount --bind /mnt/stateful_partition/root/ /root
- mkfs.ext4 -F /dev/nvme0n1
- mkdir /mnt/disks/nvme
- mount /dev/nvme0n1 /mnt/disks/nvme
- mkdir /mnt/disks/nvme/elasticsearch
- cd /etc
- git clone https://github.com/vwt-digital/securely-app.git securely-app && cd securely-app
- git apply /tmp/docker-compose.diff
- bash init.sh
- bash cloud/cloud-init.sh
- systemctl daemon-reload
- systemctl enable securely.service
- systemctl start securely.service

# Optional once-per-boot setup. For example: mounting a PD.
bootcmd:
# - fsck.ext4 -tvy /dev/[DEVICE_ID]
# - mkdir -p /mnt/disks/[MNT_DIR]
# - mount -t ext4 -O ... /dev/[DEVICE_ID] /mnt/disks/[MNT_DIR]
- '[ -d /mnt/stateful_partition/root/ ] && mount --bind /mnt/stateful_partition/root/ /root || true'
- 'mkdir /mnt/disks/nvme && mount /dev/nvme0n1 /mnt/disks/nvme || true'
